<a href="https://colab.research.google.com/github/Bellarco92/Data-Science-Bootcamp/blob/main/021_030_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 21](#1)
* [Ćwiczenie 22](#2)
* [Ćwiczenie 23](#3)
* [Ćwiczenie 24](#4)
* [Ćwiczenie 25](#5)
* [Ćwiczenie 26](#6)
* [Ćwiczenie 27](#7)
* [Ćwiczenie 28](#8)
* [Ćwiczenie 29](#9)
* [Ćwiczenie 30](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np

np.__version__

'1.21.6'

### <a name='1'></a> Ćwiczenie 21
Wygeneruj poniższą tablicę numpy. Zapisz tablicę do pliku bianarnego o nazwie _'array.npy'_ i następnie wczytaj z powrotem ten plik do innej zmiennej.


```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```


__Wskazówka:__ Użyj funkcji _np.save()_ oraz _np.load()_.

In [6]:
A = np.arange(12).reshape(-1, 4)
np.save('array.npy', A)
B = np.load('array.npy')
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### <a name='2'></a> Ćwiczenie 22
Wygeneruj ponizszą tablicę numpy:


```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```


Zapisz tablicę do pliku tekstowego o nazwie _'array.txt'_ z dokładnością do drugiego miejsca po przecinku i następnie wczytaj z powrotem ten plik do innej zmiennej.

__Wskazówka:__ Użyj funkcji _np.savetxt()_ oraz _np.loadtxt()_.


In [7]:
A = np.arange(12).reshape(-1, 4)
np.savetxt(fname='array.txt', X=A, fmt='%0.2f')
B = np.loadtxt('array.txt')
B

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

### <a name='3'></a> Ćwiczenie 23
Wygeneruj i przekształć poniższą tablicę numpy na listę.


```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```



__Wskazówka:__ Użyj metody _np.array.tolist()_.

In [10]:
A = np.arange(12).reshape(-1, 4)
A.tolist()

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]

### <a name='4'></a> Ćwiczenie 24
Podana jest poniższa tablica numpy:

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```
Używając operatora wycinania przekształć tablicę w poniższe:

* zamiana wierszy (pierwszy z ostatnim)

```
array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])
```







In [11]:
A[::-1]

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

* zamiana kolumn (odwrócona kolejność)


```
array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])
```


In [12]:
A[:, ::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

* zamiana wierszy i kolumn (odwrócone kolejności)


```
array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])
```       

In [13]:
A[::-1, ::-1]

array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

### <a name='5'></a> Ćwiczenie 25
Podaną poniżej tablicę numpy:

```
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])
```
Przekształć na tablicę:


```
array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])
```
__Wskazówka:__ Użyj funkcji _np.pad()_.





In [14]:
A = np.ones(shape=(4, 4))
np.pad(A, pad_width=1, constant_values=0)

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

### <a name='6'></a> Ćwiczenie 26
Podaną poniżej tablicę numpy:

```
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])
```
Przekształć na tablicę:


```
array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])
```
__Wskazówka:__ Użyj operatora wycinania oraz przypisz odpowiednie wartości.





In [17]:
A = np.zeros(shape=(6, 6), dtype=int)
A[::2, ::2] = 10
A[1::2, ::2] = 5
A

array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])

### <a name='7'></a> Ćwiczenie 27
Połącz podane poniżej tablice $A$ oraz $B$ w jedną.


```
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])
```




__Oczekiwany rezultat:__


```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  3,  7,  2],
       [ 0,  5,  2,  6]])
```
__Wskazówka:__ Użyj funkcji _np.append()_.


In [19]:
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])
np.append(A, B, axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  3,  7,  2],
       [ 0,  5,  2,  6]])

### <a name='8'></a> Ćwiczenie 28
Z podanych poniżej tablic $A$ i $B$ wydobądź elementy wspólne (przecięcie) tablic.

```
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])      
```



__Wskazówka:__ Użyj funkcji _np.intersect1d()_.

In [21]:
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])    
np.intersect1d(A, B)

array([0, 2, 3])

### <a name='9'></a> Ćwiczenie 29
Podana jest poniższa tablica numpy $A$.
Znajdź unikalne wartości tej tablicy.


```
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])
```


__Wskazówka:__ Użyj funkcji _np.unique()_.

In [22]:
np.unique(A)

array([0, 1, 2, 3, 4, 5, 6, 7])

### <a name='10'></a> Ćwiczenie 30
Podana jest poniższa tablica:


```
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
```



Zwróć indeksy na których stoją maksymalne wartości dla danego wiersza.

__Wskazówka:__ Użyj funkcji _np.argmax()_.

In [24]:
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
np.argmax(A, axis=0)

array([0, 2, 1])